pipeline {
    agent any
    tools {
        nodejs "Node"
    }
    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
	stage('Deploy') {
            steps {
                sh 'npm run start'
            }
        }
    }
}
